/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AbsensiRouteImport } from './routes/absensi'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IzinRouteImport } from './routes/izin'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as RiwayatRouteImport } from './routes/riwayat'
import { Route as AdminAbsensiRouteImport } from './routes/admin/absensi'
import { Route as AdminGuruRouteImport } from './routes/admin/guru'
import { Route as AdminIzinRouteImport } from './routes/admin/izin'
import { Route as AdminLogRouteImport } from './routes/admin/log'
import { Route as AdminPengaturanRouteImport } from './routes/admin/pengaturan'
import { Route as AdminPengumumanRouteImport } from './routes/admin/pengumuman'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AbsensiRoute = AbsensiRouteImport.update({
  id: '/absensi',
  path: '/absensi',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IzinRoute = IzinRouteImport.update({
  id: '/izin',
  path: '/izin',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const RiwayatRoute = RiwayatRouteImport.update({
  id: '/riwayat',
  path: '/riwayat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAbsensiRoute = AdminAbsensiRouteImport.update({
  id: '/admin/absensi',
  path: '/admin/absensi',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGuruRoute = AdminGuruRouteImport.update({
  id: '/admin/guru',
  path: '/admin/guru',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIzinRoute = AdminIzinRouteImport.update({
  id: '/admin/izin',
  path: '/admin/izin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLogRoute = AdminLogRouteImport.update({
  id: '/admin/log',
  path: '/admin/log',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPengaturanRoute = AdminPengaturanRouteImport.update({
  id: '/admin/pengaturan',
  path: '/admin/pengaturan',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPengumumanRoute = AdminPengumumanRouteImport.update({
  id: '/admin/pengumuman',
  path: '/admin/pengumuman',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/absensi': typeof AbsensiRoute
  '/dashboard': typeof DashboardRoute
  '/izin': typeof IzinRoute
  '/profil': typeof ProfilRoute
  '/riwayat': typeof RiwayatRoute
  '/admin/absensi': typeof AdminAbsensiRoute
  '/admin/guru': typeof AdminGuruRoute
  '/admin/izin': typeof AdminIzinRoute
  '/admin/log': typeof AdminLogRoute
  '/admin/pengaturan': typeof AdminPengaturanRoute
  '/admin/pengumuman': typeof AdminPengumumanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/absensi': typeof AbsensiRoute
  '/dashboard': typeof DashboardRoute
  '/izin': typeof IzinRoute
  '/profil': typeof ProfilRoute
  '/riwayat': typeof RiwayatRoute
  '/admin/absensi': typeof AdminAbsensiRoute
  '/admin/guru': typeof AdminGuruRoute
  '/admin/izin': typeof AdminIzinRoute
  '/admin/log': typeof AdminLogRoute
  '/admin/pengaturan': typeof AdminPengaturanRoute
  '/admin/pengumuman': typeof AdminPengumumanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/absensi': typeof AbsensiRoute
  '/dashboard': typeof DashboardRoute
  '/izin': typeof IzinRoute
  '/profil': typeof ProfilRoute
  '/riwayat': typeof RiwayatRoute
  '/admin/absensi': typeof AdminAbsensiRoute
  '/admin/guru': typeof AdminGuruRoute
  '/admin/izin': typeof AdminIzinRoute
  '/admin/log': typeof AdminLogRoute
  '/admin/pengaturan': typeof AdminPengaturanRoute
  '/admin/pengumuman': typeof AdminPengumumanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/absensi'
    | '/dashboard'
    | '/izin'
    | '/profil'
    | '/riwayat'
    | '/admin/absensi'
    | '/admin/guru'
    | '/admin/izin'
    | '/admin/log'
    | '/admin/pengaturan'
    | '/admin/pengumuman'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/absensi'
    | '/dashboard'
    | '/izin'
    | '/profil'
    | '/riwayat'
    | '/admin/absensi'
    | '/admin/guru'
    | '/admin/izin'
    | '/admin/log'
    | '/admin/pengaturan'
    | '/admin/pengumuman'
  id:
    | '__root__'
    | '/'
    | '/absensi'
    | '/dashboard'
    | '/izin'
    | '/profil'
    | '/riwayat'
    | '/admin/absensi'
    | '/admin/guru'
    | '/admin/izin'
    | '/admin/log'
    | '/admin/pengaturan'
    | '/admin/pengumuman'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbsensiRoute: typeof AbsensiRoute
  DashboardRoute: typeof DashboardRoute
  IzinRoute: typeof IzinRoute
  ProfilRoute: typeof ProfilRoute
  RiwayatRoute: typeof RiwayatRoute
  AdminAbsensiRoute: typeof AdminAbsensiRoute
  AdminGuruRoute: typeof AdminGuruRoute
  AdminIzinRoute: typeof AdminIzinRoute
  AdminLogRoute: typeof AdminLogRoute
  AdminPengaturanRoute: typeof AdminPengaturanRoute
  AdminPengumumanRoute: typeof AdminPengumumanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/absensi': {
      id: '/absensi'
      path: '/absensi'
      fullPath: '/absensi'
      preLoaderRoute: typeof AbsensiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/izin': {
      id: '/izin'
      path: '/izin'
      fullPath: '/izin'
      preLoaderRoute: typeof IzinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/riwayat': {
      id: '/riwayat'
      path: '/riwayat'
      fullPath: '/riwayat'
      preLoaderRoute: typeof RiwayatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/absensi': {
      id: '/admin/absensi'
      path: '/admin/absensi'
      fullPath: '/admin/absensi'
      preLoaderRoute: typeof AdminAbsensiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/guru': {
      id: '/admin/guru'
      path: '/admin/guru'
      fullPath: '/admin/guru'
      preLoaderRoute: typeof AdminGuruRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/izin': {
      id: '/admin/izin'
      path: '/admin/izin'
      fullPath: '/admin/izin'
      preLoaderRoute: typeof AdminIzinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/log': {
      id: '/admin/log'
      path: '/admin/log'
      fullPath: '/admin/log'
      preLoaderRoute: typeof AdminLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pengaturan': {
      id: '/admin/pengaturan'
      path: '/admin/pengaturan'
      fullPath: '/admin/pengaturan'
      preLoaderRoute: typeof AdminPengaturanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pengumuman': {
      id: '/admin/pengumuman'
      path: '/admin/pengumuman'
      fullPath: '/admin/pengumuman'
      preLoaderRoute: typeof AdminPengumumanRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbsensiRoute: AbsensiRoute,
  DashboardRoute: DashboardRoute,
  IzinRoute: IzinRoute,
  ProfilRoute: ProfilRoute,
  RiwayatRoute: RiwayatRoute,
  AdminAbsensiRoute: AdminAbsensiRoute,
  AdminGuruRoute: AdminGuruRoute,
  AdminIzinRoute: AdminIzinRoute,
  AdminLogRoute: AdminLogRoute,
  AdminPengaturanRoute: AdminPengaturanRoute,
  AdminPengumumanRoute: AdminPengumumanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
